# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d559e4897655df570c646aa3fd842995fc1667edd596adecbf982e58aa20c30b20506888942b56a6cbe9cfe56b7d6f48f2164de7fc859ec3850ccff12a7edaf

test:
  secret_key_base: a26ca89faae4a5b018c45d5c333646ff569f11cd83786bdcbf7821813c97033032b4a66e21a57c6c7b1f4e7e9b1ab55d5996ca8bf4b70bd5acccacfad8ce451d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
